#!/usr/bin/env ruby
# frozen_string_literal: true

require 'clamp'
require 'date'

require_relative '../lib/attend'

parse_date = Date.method(:parse)

Clamp do
  option '--email', 'EMAIL', 'employee email id', required: true
  option '--check_in', 'CHECK_IN', 'check in time', default: '9:00'
  option '--check_out', 'CHECK_OUT', 'check out time', default: '17:00'
  option '--from', 'FROM', 'date of the first work day', default: Date.today, &parse_date
  option '--to', 'TO', 'date of the las work day', default: Date.today, &parse_date
  option '--dry', :flag, 'enables dry run'
  option '--verbose', :flag, 'print verbose error message'

  def execute
    Attend.register(email: email, from: from, to: to, check_in: check_in, check_out: check_out, dry_run: dry?)
  rescue StandardError => e
    if verbose?
      puts e.full_message
    else
      puts e.message
    end

    exit 1
  end
end
